// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

com.eterultimate.eteruee.data.model.Conversation
com.eterultimate.eteruee.data.model.MessageNode
com.eterultimate.eteruee.ai.ui.UIMessage
com.eterultimate.eteruee.ai.ui.UIMessageChoice
com.eterultimate.eteruee.ai.ui.MessageChunk
com.eterultimate.eteruee.ai.ui.UIMessageAnnotation
com.eterultimate.eteruee.ai.ui.ToolApprovalState
com.eterultimate.eteruee.ai.core.TokenUsage