package com.eterultimate.eteruee.ui.theme.presets

import androidx.compose.material3.Text
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.stringResource
import com.eterultimate.eteruee.R
import com.eterultimate.eteruee.ui.theme.PresetTheme

val SoftGlassThemePreset by lazy {
    PresetTheme(
        id = "soft-glass",
        name = { Text(stringResource(id = R.string.theme_name_soft_glass)) },
        standardLight = lightColorScheme(
            primary = Color(0xFF2478A8),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD7EEF8),
            onPrimaryContainer = Color(0xFF08364B),
            secondary = Color(0xFF5B6F82),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE2EBF2),
            onSecondaryContainer = Color(0xFF172734),
            tertiary = Color(0xFF7865A8),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFE9DFFF),
            onTertiaryContainer = Color(0xFF2D214D),
            background = Color(0xFFF5FAFD),
            onBackground = Color(0xFF17212B),
            surface = Color(0xFFF8FBFD),
            onSurface = Color(0xFF17212B),
            surfaceVariant = Color(0xFFE4EDF3),
            onSurfaceVariant = Color(0xFF45535E),
            outline = Color(0xFFB6C6D1),
            outlineVariant = Color(0xFFD6E0E7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF3F8FB),
            surfaceContainer = Color(0xFFEDF4F8),
            surfaceContainerHigh = Color(0xFFE7EFF4),
            surfaceContainerHighest = Color(0xFFDDE8EF),
            surfaceBright = Color(0xFFFFFFFF),
            surfaceDim = Color(0xFFD8E4EB),
        ),
        standardDark = darkColorScheme(
            primary = Color(0xFF7FD2F4),
            onPrimary = Color(0xFF002D43),
            primaryContainer = Color(0xFF164E68),
            onPrimaryContainer = Color(0xFFCCF0FF),
            secondary = Color(0xFFB9CBD8),
            onSecondary = Color(0xFF24333F),
            secondaryContainer = Color(0xFF324756),
            onSecondaryContainer = Color(0xFFD9E7F0),
            tertiary = Color(0xFFD2C2FF),
            onTertiary = Color(0xFF38265F),
            tertiaryContainer = Color(0xFF503D78),
            onTertiaryContainer = Color(0xFFEADDFF),
            background = Color(0xFF101922),
            onBackground = Color(0xFFE4EEF5),
            surface = Color(0xFF121C25),
            onSurface = Color(0xFFE4EEF5),
            surfaceVariant = Color(0xFF3E4B55),
            onSurfaceVariant = Color(0xFFC4D0D8),
            outline = Color(0xFF8E9EA8),
            outlineVariant = Color(0xFF3E4B55),
            surfaceContainerLowest = Color(0xFF0B1118),
            surfaceContainerLow = Color(0xFF151F28),
            surfaceContainer = Color(0xFF1A2530),
            surfaceContainerHigh = Color(0xFF23313D),
            surfaceContainerHighest = Color(0xFF2C3A46),
            surfaceBright = Color(0xFF334653),
            surfaceDim = Color(0xFF101922),
        ),
    )
}

val MinimalThemePreset by lazy {
    PresetTheme(
        id = "minimal",
        name = { Text(stringResource(id = R.string.theme_name_minimal)) },
        standardLight = lightColorScheme(
            primary = Color(0xFF111111),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFE8E8E8),
            onPrimaryContainer = Color(0xFF111111),
            secondary = Color(0xFF5F6368),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFEDEDED),
            onSecondaryContainer = Color(0xFF1F1F1F),
            tertiary = Color(0xFF777777),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFF0F0F0),
            onTertiaryContainer = Color(0xFF202020),
            background = Color.White,
            onBackground = Color(0xFF111111),
            surface = Color.White,
            onSurface = Color(0xFF111111),
            surfaceVariant = Color(0xFFF2F2F2),
            onSurfaceVariant = Color(0xFF555555),
            outline = Color(0xFFD2D2D2),
            outlineVariant = Color(0xFFE8E8E8),
            surfaceContainerLowest = Color.White,
            surfaceContainerLow = Color(0xFFFAFAFA),
            surfaceContainer = Color(0xFFF6F6F6),
            surfaceContainerHigh = Color(0xFFF0F0F0),
            surfaceContainerHighest = Color(0xFFEAEAEA),
            surfaceBright = Color.White,
            surfaceDim = Color(0xFFE7E7E7),
        ),
        standardDark = darkColorScheme(
            primary = Color(0xFFEDEDED),
            onPrimary = Color(0xFF111111),
            primaryContainer = Color(0xFF2A2A2A),
            onPrimaryContainer = Color(0xFFF3F3F3),
            secondary = Color(0xFFC7C7C7),
            onSecondary = Color(0xFF222222),
            secondaryContainer = Color(0xFF303030),
            onSecondaryContainer = Color(0xFFE7E7E7),
            tertiary = Color(0xFFA8A8A8),
            onTertiary = Color(0xFF1A1A1A),
            tertiaryContainer = Color(0xFF292929),
            onTertiaryContainer = Color(0xFFE0E0E0),
            background = Color(0xFF111111),
            onBackground = Color(0xFFEDEDED),
            surface = Color(0xFF121212),
            onSurface = Color(0xFFEDEDED),
            surfaceVariant = Color(0xFF2C2C2C),
            onSurfaceVariant = Color(0xFFC8C8C8),
            outline = Color(0xFF444444),
            outlineVariant = Color(0xFF2A2A2A),
            surfaceContainerLowest = Color(0xFF0C0C0C),
            surfaceContainerLow = Color(0xFF171717),
            surfaceContainer = Color(0xFF1D1D1D),
            surfaceContainerHigh = Color(0xFF242424),
            surfaceContainerHighest = Color(0xFF2C2C2C),
            surfaceBright = Color(0xFF343434),
            surfaceDim = Color(0xFF111111),
        ),
    )
}

val ClaudeThemePreset by lazy {
    PresetTheme(
        id = "claude",
        name = { Text(stringResource(id = R.string.theme_name_claude)) },
        standardLight = lightColorScheme(
            primary = Color(0xFFB45F3A),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFFFDBCA),
            onPrimaryContainer = Color(0xFF3D1709),
            secondary = Color(0xFF77574A),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFFFDBCE),
            onSecondaryContainer = Color(0xFF2C160E),
            tertiary = Color(0xFF6C6040),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFF5E4B7),
            onTertiaryContainer = Color(0xFF241A04),
            background = Color(0xFFFCF7EF),
            onBackground = Color(0xFF231A14),
            surface = Color(0xFFFCF7EF),
            onSurface = Color(0xFF231A14),
            surfaceVariant = Color(0xFFF0E0D5),
            onSurfaceVariant = Color(0xFF52443D),
            outline = Color(0xFF84736A),
            outlineVariant = Color(0xFFD5C4BA),
            surfaceContainerLowest = Color.White,
            surfaceContainerLow = Color(0xFFF9F1E8),
            surfaceContainer = Color(0xFFF3EADF),
            surfaceContainerHigh = Color(0xFFEDE3D8),
            surfaceContainerHighest = Color(0xFFE6DACE),
            surfaceBright = Color(0xFFFFFAF4),
            surfaceDim = Color(0xFFE4D8CD),
        ),
        standardDark = darkColorScheme(
            primary = Color(0xFFFFB596),
            onPrimary = Color(0xFF5C210C),
            primaryContainer = Color(0xFF813A1F),
            onPrimaryContainer = Color(0xFFFFDBCA),
            secondary = Color(0xFFE7BDAE),
            onSecondary = Color(0xFF442A21),
            secondaryContainer = Color(0xFF5D4035),
            onSecondaryContainer = Color(0xFFFFDBCE),
            tertiary = Color(0xFFD8C895),
            onTertiary = Color(0xFF3B2F11),
            tertiaryContainer = Color(0xFF534621),
            onTertiaryContainer = Color(0xFFF5E4B7),
            background = Color(0xFF1F1A16),
            onBackground = Color(0xFFECE0D7),
            surface = Color(0xFF1F1A16),
            onSurface = Color(0xFFECE0D7),
            surfaceVariant = Color(0xFF52443D),
            onSurfaceVariant = Color(0xFFD7C3B8),
            outline = Color(0xFF9E8D84),
            outlineVariant = Color(0xFF52443D),
            surfaceContainerLowest = Color(0xFF16110E),
            surfaceContainerLow = Color(0xFF241D19),
            surfaceContainer = Color(0xFF2A221D),
            surfaceContainerHigh = Color(0xFF352B25),
            surfaceContainerHighest = Color(0xFF40342D),
            surfaceBright = Color(0xFF4A3C34),
            surfaceDim = Color(0xFF1F1A16),
        ),
    )
}

val ChatGptThemePreset by lazy {
    PresetTheme(
        id = "chatgpt",
        name = { Text(stringResource(id = R.string.theme_name_chatgpt)) },
        standardLight = lightColorScheme(
            primary = Color(0xFF0F8A64),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFBCEEDC),
            onPrimaryContainer = Color(0xFF002116),
            secondary = Color(0xFF4D6358),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFCFE9DA),
            onSecondaryContainer = Color(0xFF0A1F16),
            tertiary = Color(0xFF3E6474),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFC1E9FB),
            onTertiaryContainer = Color(0xFF001F2B),
            background = Color.White,
            onBackground = Color(0xFF111715),
            surface = Color.White,
            onSurface = Color(0xFF111715),
            surfaceVariant = Color(0xFFDCE5DE),
            onSurfaceVariant = Color(0xFF404942),
            outline = Color(0xFF707972),
            outlineVariant = Color(0xFFC0C9C1),
            surfaceContainerLowest = Color.White,
            surfaceContainerLow = Color(0xFFF5F7F5),
            surfaceContainer = Color(0xFFEFF3EF),
            surfaceContainerHigh = Color(0xFFE9EDE9),
            surfaceContainerHighest = Color(0xFFE1E7E2),
            surfaceBright = Color.White,
            surfaceDim = Color(0xFFDCE5DE),
        ),
        standardDark = darkColorScheme(
            primary = Color(0xFF61D8AD),
            onPrimary = Color(0xFF003828),
            primaryContainer = Color(0xFF00513B),
            onPrimaryContainer = Color(0xFFBCEEDC),
            secondary = Color(0xFFB3CCBE),
            onSecondary = Color(0xFF20352B),
            secondaryContainer = Color(0xFF364B40),
            onSecondaryContainer = Color(0xFFCFE9DA),
            tertiary = Color(0xFFA5CDDC),
            onTertiary = Color(0xFF073544),
            tertiaryContainer = Color(0xFF254B5B),
            onTertiaryContainer = Color(0xFFC1E9FB),
            background = Color(0xFF111715),
            onBackground = Color(0xFFE1E9E3),
            surface = Color(0xFF111715),
            onSurface = Color(0xFFE1E9E3),
            surfaceVariant = Color(0xFF404942),
            onSurfaceVariant = Color(0xFFC0C9C1),
            outline = Color(0xFF8A938B),
            outlineVariant = Color(0xFF404942),
            surfaceContainerLowest = Color(0xFF0B100E),
            surfaceContainerLow = Color(0xFF171D1A),
            surfaceContainer = Color(0xFF1B211E),
            surfaceContainerHigh = Color(0xFF252B28),
            surfaceContainerHighest = Color(0xFF303633),
            surfaceBright = Color(0xFF383E3B),
            surfaceDim = Color(0xFF111715),
        ),
    )
}

val GeminiThemePreset by lazy {
    PresetTheme(
        id = "gemini",
        name = { Text(stringResource(id = R.string.theme_name_gemini)) },
        standardLight = lightColorScheme(
            primary = Color(0xFF1A73E8),
            onPrimary = Color.White,
            primaryContainer = Color(0xFFD7E2FF),
            onPrimaryContainer = Color(0xFF001B3F),
            secondary = Color(0xFF5B5D72),
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFE0E1F9),
            onSecondaryContainer = Color(0xFF181A2C),
            tertiary = Color(0xFF007B83),
            onTertiary = Color.White,
            tertiaryContainer = Color(0xFFA9EEF3),
            onTertiaryContainer = Color(0xFF002023),
            background = Color(0xFFFBFCFF),
            onBackground = Color(0xFF191B20),
            surface = Color(0xFFFBFCFF),
            onSurface = Color(0xFF191B20),
            surfaceVariant = Color(0xFFE1E2EC),
            onSurfaceVariant = Color(0xFF44464F),
            outline = Color(0xFF757780),
            outlineVariant = Color(0xFFC5C6D0),
            surfaceContainerLowest = Color.White,
            surfaceContainerLow = Color(0xFFF4F7FF),
            surfaceContainer = Color(0xFFEEF2FA),
            surfaceContainerHigh = Color(0xFFE8ECF4),
            surfaceContainerHighest = Color(0xFFE1E6EF),
            surfaceBright = Color.White,
            surfaceDim = Color(0xFFD9DEE8),
        ),
        standardDark = darkColorScheme(
            primary = Color(0xFFAFC6FF),
            onPrimary = Color(0xFF002E67),
            primaryContainer = Color(0xFF0C4D9F),
            onPrimaryContainer = Color(0xFFD7E2FF),
            secondary = Color(0xFFC4C5DD),
            onSecondary = Color(0xFF2D2F42),
            secondaryContainer = Color(0xFF44465A),
            onSecondaryContainer = Color(0xFFE0E1F9),
            tertiary = Color(0xFF82D2D9),
            onTertiary = Color(0xFF00363A),
            tertiaryContainer = Color(0xFF005057),
            onTertiaryContainer = Color(0xFFA9EEF3),
            background = Color(0xFF111318),
            onBackground = Color(0xFFE3E7EF),
            surface = Color(0xFF111318),
            onSurface = Color(0xFFE3E7EF),
            surfaceVariant = Color(0xFF44464F),
            onSurfaceVariant = Color(0xFFC5C6D0),
            outline = Color(0xFF8F9099),
            outlineVariant = Color(0xFF44464F),
            surfaceContainerLowest = Color(0xFF0B0E12),
            surfaceContainerLow = Color(0xFF181B20),
            surfaceContainer = Color(0xFF1C1F25),
            surfaceContainerHigh = Color(0xFF272A30),
            surfaceContainerHighest = Color(0xFF32353B),
            surfaceBright = Color(0xFF3A3E45),
            surfaceDim = Color(0xFF111318),
        ),
    )
}
